# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20170227_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
