# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20170227_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
