# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_post_posttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('name', models.TextField(default='')),
                ('postType', models.TextField(default='Video')),
                ('score', models.IntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Source')),
            ],
        ),
    ]
