# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_prepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepost',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
