# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_prepost_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoredPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('name', models.TextField(default='')),
                ('postType', models.TextField(default='Video')),
                ('score', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sources', models.ManyToManyField(to='feed.Source')),
            ],
        ),
    ]
