# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_remove_prepost_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrePost',
            new_name='RawPost',
        ),
    ]
