# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_remove_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rawpost',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scoredpost',
            name='name',
        ),
    ]
