# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_auto_20170303_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='New Group')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feed.SourceGroup'),
            preserve_default=False,
        ),
    ]
