# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_auto_20170306_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='rssable',
            field=models.BooleanField(default=False),
        ),
    ]
